### ISSUE TITLE
property sd2p and sd2n TypeError: 'function' object is not subscriptable

### ISSUE THREAD

**Issue by huang-git** [elyase/masstable#1]
17         key = str(args) + str(kwargs)
     18         if key not in cache:
---> 19             cache[key] = obj(*args, **kwargs)
     20         return cache[key]
     21     return memoizer

493         """
494         idx = [(x[0] + 0, x[1] + 2) for x in self.df.index]
--> 495         values = self.s2n.values - self.s2n.loc[idx].values
496         return Table(df=pd.Series(values, index=self.df.index, name='ds2n' + '(' + self.name + ')'))

**Comment by elyase** [comment]
Thanks for reporting. Should be fixed in the latest version `pip install -U masstable`.
